# Generated by Django 4.2.3 on 2024-03-14 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericalert',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 2, 16, 1, 513002, tzinfo=datetime.timezone.utc), verbose_name='created_at'),
        ),
    ]
